# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20170427_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.MyUser'),
        ),
        migrations.AddField(
            model_name='follow',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_from_id', to='instagram.MyUser'),
        ),
        migrations.AddField(
            model_name='follow',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_id', to='instagram.MyUser'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='follow_table',
            field=models.ManyToManyField(through='instagram.Follow', to='instagram.MyUser'),
        ),
    ]
