# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20171206_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='from_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='to_id',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='owner_user',
        ),
    ]
